#!/bin/sh
export XDG_CURRENT_DESKTOP=OPENBOX
SET_DESKTOP=$(readlink -f $HOME/.config/openbox/set-desktop)

[ $(pidof pcmanfm) ] && killall -9 pcmanfm

# Provides the desktop of choice, e.g. tint2 left icon panel or rox pinboard
# Can be selected from Menu > Desktop Manager
. $HOME/.config/openbox/set-desktop
sleep 2

#chpupsocket $USER:$USER &

parcellite &
#sleep 1

#frisbee-tray &
#wicd-gtk --tray &

#volumeicon &

if [ "$SET_DESKTOP" != "$HOME/.config/openbox/pcman" ]; then
# Pre-load menu
xdotool mousemove 0 0
xdotool key ctrl+alt+space
xdotool mousemove 300 300
openbox --reconfigure
fi

#desktop_drive_icons &
sleep 8
if [ -f /mnt/live/tmp/modules ]; then
conky -c ~/.conkyrc-port &
else
conky -c ~/.conkyrc-live &
fi
#alsamixertray &
