#!/bin/sh
#Thunar --daemon &
#xfdesktop &
#xfce4-panel &
[ $(pidof pcmanfm) ] && killall -9 pcmanfm
pcmanfm --desktop &
sleep 2
lxpanel &
#xfce4-clipman &
sleep 1
#frisbee-tray &
sleep 8
if [ -f /mnt/live/tmp/modules ]; then
conky -c ~/.conkyrc-port &
else
conky -c ~/.conkyrc-live &
fi
#wait $!
#volumeicon
